spring:
  boot:
    admin:
      client:
        url: http://localhost:9001

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.filio: DEBUG  
