spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
  boot:
    admin:
      client:
        url: http://localhost:9001
        username: instance-user
        password: instance-password
        instance:
          metadata:
            user.name: instance-user
            user.password: instance-user

server:
    port: 9002

logging:
  level:
    org.filio: DEBUG
