server:
  port: 8881

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.filio: DEBUG

loadBalancer:
  fileTransfer:
    name: File Transfer
    url: http://localhost:8001
    resourceName: files