server:
  port: 8881

loadBalancer:
  fileTransfer:
    name: File Transfer Service
    url: http://localhost:8001

spring:
  application:
    name: gateway
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:9000}
  boot:
    admin:
      client:
        url: http://localhost:9001

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.filio: DEBUG
