server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2

spring:
  application:
    name: gateway

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

loggin:
  level:
    org.fts: DEBUG
