spring:
  security:
    user:
      name: admin-server-user
      password: admin-server-password
  boot:
    admin:
      client:
        username: instance-user2
        password: instance-password2

logging:
  level:
    org.filio: DEBUG
