spring:
  boot:
    admin:
      client:
        url: http://localhost:9001
        username: admin-server-user
        password: admin-server-password
        instance:
          metadata:
            user.name: admin-client-user
            user.password: admin-client-password

logging:
  level:
    org.filio: DEBUG
