spring:
  boot:
    admin:
      client:
        url: http://localhost:9001
        username: admin-server-user
        password: admin-server-password

logging:
  level:
    org.filio: DEBUG
    org.springframework: DEBUG
