spring:
  security:
    user:
      name: instance
      password: instance
  boot:
    admin:
      client:
        username: admin
        password: admin
        instance:
          metadata:
            user.name: instance
            user.password: instance

logging:
  level:
    org.filio: DEBUG
