spring:
  boot:
    admin:
      client:
        instance:
          metadata:
            user.name: admin-client-user
            user.password: admin-client-password

logging:
  level:
    org.filio: DEBUG
