spring:
  security:
    user:
      name: instance-user2
      password: instance-password2
  boot:
    admin:
      client:
        username: admin-server-user
        password: admin-server-password
        instance:
          metadata:
            user.name: instance-user2
            user.password: instance-password2

logging:
  level:
    org.filio: DEBUG
