server:
  port: ${PORT:8761}

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl: 
      defaulZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
  instance:
    leaseRenewalIntervalInSeconds: 10

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      context-path: /admin
