server:
  port: 9001

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  boot:
    admin:
      context-path: /

logging:
  level:
    org.filio: DEBUG  
