spring:
  application:
    name: admin
  security:
    user:
      name: admin-user
      password: admin-password
  boot:
    admin:
      client:
        instance:
          metadata:
            user.name: instance-user
            user.password: instance-password
      context-path: /

server:
  port: 9001

logging:
  level:
    org.filio: DEBUG  
