server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2

spring:
  application:
    name: gateway

serviceDiscovery:
  fileTransfer:
    name: File Transfer Service
    url: http://file-transfer

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.filio: DEBUG
