server:
  port: 8001

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.filio: DEBUG

service:
  name: File Transfer
  url: http://file-transfer
  resourceUri: /files/

file-transfer:
  ribbon:
    eureka:
      enabled: true

