server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    instanceId: ${spring.application.name}:{$spring.application.instance_id:${random.value}}

spring:
  application:
    name: file-transfer

management:
  endpoints:
    web:
      exposure:
        include: "*"

minio:
  serverName: http://localhost
  serverPort: 9000
  accessKey: my-access-key
  secretKey: my-secret-key
  bucketName: my-bucket

logging:
  level:
    org.filio: DEBUG  

