server:
  port: ${PORT:0}

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.filio: DEBUG

minio:
  serverName: http://localhost
  serverPort: 9000
  accessKey: 5J0MM2M0NXG1UQB37P1W
  secretKey: bFqGV6nKrgFahJxOJZu81tOPMzkd1rqLzOe2c0ao
  bucketName: my-bucket

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      database: filio
